In [1]:
import os
# from PIL import Image
import pandas as pd
import numpy as np
import torch

In [2]:
import cv2 # conda install -c menpo opencv3
#sudo apt update
#sudo apt install python3-opencv

In [5]:
!pip install opencv-python

     |████████████████████████████████| 28.7MB 5.1MB/s eta 0:00:012


In [15]:
!pip install torch

     |████████████████████████████████| 773.1MB 74kB/s  eta 0:00:012  |                                | 522kB 303kB/s eta 0:42:29     |█▏                              | 27.5MB 4.5MB/s eta 0:02:45     |█▊                              | 42.0MB 7.0MB/s eta 0:01:44     |█▊                              | 42.9MB 318kB/s eta 0:38:17     |██▊                             | 66.4MB 4.6MB/s eta 0:02:35     |███                             | 75.0MB 8.4MB/s eta 0:01:23     |███▏                            | 76.0MB 628kB/s eta 0:18:29     |███▊                            | 90.1MB 2.7MB/s eta 0:04:15     |███▊                            | 90.9MB 2.7MB/s eta 0:04:15     |████▊                           | 114.8MB 3.9MB/s eta 0:02:48     |█████                           | 122.5MB 1.9MB/s eta 0:05:48     |█████▏                          | 125.8MB 8.5MB/s eta 0:01:17     |█████▊                          | 137.3MB 9.0MB/s eta 0:01:11     |████████                        | 195.1MB 9.3MB/s eta 0:01:03     |█

In [37]:
os.getcwd()

'/home/andreybocharnikov/ML/sir'

In [68]:
os.chdir('indoorCVPR_09')

In [4]:
os.getcwd()

'/home/andreybocharnikov/ML/sir'

In [9]:
from torch.utils.data import DataLoader, Dataset

In [6]:
id_ = 0
os.mkdir(os.getcwd() + '/mapped_ids')
for current_dir, dirs, files in os.walk(os.getcwd() + '/indoorCVPR_09'):
    for file in files:
        cur_name = str(id_) + '.jpg'
        os.rename(current_dir + '/' + file, os.getcwd() + '/mapped_ids/' + cur_name)
        id_ += 1

In [7]:
id_

15620

In [34]:
class ImageDataSet(Dataset):
    def __init__(self, class_):
        self.path = ''
        if class_ == 'indoors':
            self.path = os.getcwd() + '/mapped_ids'
        elif class_ == 'outdoors':
            self.path = os.getcwd() + '/outdoor'
        else:
            raise Exception()
        self.permutation = np.random.permutation(id_)
    def __len__(self):
        return id_
    def __getitem__(self, id):
        img = cv2.imread(self.path + '/' + str(self.permutation[id]) + '.jpg', cv2.COLOR_BGR2RGB)
        print(self.path + '/' + str(self.permutation[id]) + '.jpg', img)
        return torch.tensor(np.transpose(img, (2, 0, 1)))

In [35]:
loader = ImageDataSet('indoors')

In [36]:
loader.__getitem__(4)

/home/andreybocharnikov/ML/sir/mapped_ids/706.jpg [[[27 45 74]
  [ 9 27 56]
  [ 6 20 48]
  ...
  [ 4 17 31]
  [ 4 18 30]
  [12 26 38]]

 [[27 45 74]
  [ 9 27 56]
  [ 6 20 48]
  ...
  [ 5 18 32]
  [ 5 19 31]
  [12 26 38]]

 [[27 45 74]
  [ 9 27 56]
  [ 7 21 49]
  ...
  [ 5 18 32]
  [ 4 18 30]
  [11 25 37]]

 ...

 [[ 4 15 37]
  [ 4 15 37]
  [ 5 16 38]
  ...
  [10 22 46]
  [22 36 65]
  [27 42 74]]

 [[ 4 15 37]
  [ 4 15 37]
  [ 5 16 38]
  ...
  [12 24 48]
  [23 37 66]
  [25 43 74]]

 [[ 4 15 37]
  [ 4 15 37]
  [ 5 16 38]
  ...
  [13 25 49]
  [21 37 66]
  [25 43 74]]]


tensor([[[27,  9,  6,  ...,  4,  4, 12],
         [27,  9,  6,  ...,  5,  5, 12],
         [27,  9,  7,  ...,  5,  4, 11],
         ...,
         [ 4,  4,  5,  ..., 10, 22, 27],
         [ 4,  4,  5,  ..., 12, 23, 25],
         [ 4,  4,  5,  ..., 13, 21, 25]],

        [[45, 27, 20,  ..., 17, 18, 26],
         [45, 27, 20,  ..., 18, 19, 26],
         [45, 27, 21,  ..., 18, 18, 25],
         ...,
         [15, 15, 16,  ..., 22, 36, 42],
         [15, 15, 16,  ..., 24, 37, 43],
         [15, 15, 16,  ..., 25, 37, 43]],

        [[74, 56, 48,  ..., 31, 30, 38],
         [74, 56, 48,  ..., 32, 31, 38],
         [74, 56, 49,  ..., 32, 30, 37],
         ...,
         [37, 37, 38,  ..., 46, 65, 74],
         [37, 37, 38,  ..., 48, 66, 74],
         [37, 37, 38,  ..., 49, 66, 74]]], dtype=torch.uint8)

In [39]:
'''class ImageDataSet(Dataset):
    def __init__(self, class_):
        if class_ == 'indoors':
            path = os.getcwd() + '/indoorCVPR_09'
        elif class_ == 'outdoors':
            path = os.getcwd() + '/outdoor'
        else:
            raise Exception()
        #print(path)
        cnt = 0
        sum_ = 0
        #self.data = list()
        for current_dir, dirs, files in os.walk(path):
            # print(current_dir, file, type(current_dir), type(file))
            for file in files:
                img = cv2.imread(current_dir +  '/' + file, cv2.COLOR_BGR2RGB)
                # print(current_dir +  '/' + file)
                # print(len(img.shape), current_dir +  '/' + file)
                if img is None:
                    continue
                if (len(img.shape) == 3): #check RGB
                    # self.data.append(torch.Tensor(np.transpose(img, (2, 0, 1))))
                    sum_ += 1
                else:
                    cnt += 1
                    sum_ += 1
        print ('RGB is', 1 - cnt / sum_)
    def __len__(self):
        return len(self.dataSet.data)
    def __getitem__(self, id):
        return self.dataSet.data[id]
'''

"class ImageDataSet(Dataset):\n    def __init__(self, class_):\n        if class_ == 'indoors':\n            path = os.getcwd() + '/indoorCVPR_09'\n        elif class_ == 'outdoors':\n            path = os.getcwd() + '/outdoor'\n        else:\n            raise Exception()\n        #print(path)\n        cnt = 0\n        sum_ = 0\n        #self.data = list()\n        for current_dir, dirs, files in os.walk(path):\n            # print(current_dir, file, type(current_dir), type(file))\n            for file in files:\n                img = cv2.imread(current_dir +  '/' + file, cv2.COLOR_BGR2RGB)\n                # print(current_dir +  '/' + file)\n                # print(len(img.shape), current_dir +  '/' + file)\n                if img is None:\n                    continue\n                if (len(img.shape) == 3): #check RGB\n                    # self.data.append(torch.Tensor(np.transpose(img, (2, 0, 1))))\n                    sum_ += 1\n                else:\n                    cnt +

In [3]:
'''class DataSetLoader():
    def __init__(self, class_, batch_size=0.05):
        self.dataSet = ''
        if class_ == 'indoors':
            self.dataSet = ImageDataSet(os.getcwd() + 'indoorCVPR_09')
        elif class_ == 'outdoors':
            self.dataSet = ImageDataSet(os.getcwd() + 'outdoor')
        else:
            raise Exception()
'''    
# TODO batch_size float, int

"class DataSetLoader():\n    def __init__(self, class_, batch_size=0.05):\n        self.dataSet = ''\n        if class_ == 'indoors':\n            self.dataSet = ImageDataSet(os.getcwd() + 'indoorCVPR_09')\n        elif class_ == 'outdoors':\n            self.dataSet = ImageDataSet(os.getcwd() + 'outdoor')\n        else:\n            raise Exception()\n"